# Generated by Django 3.2 on 2021-05-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20210502_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maha',
            old_name='position',
            new_name='jkelamin',
        ),
        migrations.RenameField(
            model_name='maha',
            old_name='Mobile',
            new_name='kelas',
        ),
        migrations.RenameField(
            model_name='maha',
            old_name='fullname',
            new_name='nama',
        ),
    ]
